version: "2"
linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
formatters:
  enable:
    - gofmt
issues:
  exclude-files:
    - _test\.go
  max-issues-per-linter: 0
  max-same-issues: 0
