//go:build integration

// generated_keys_external_test.go — package-external (h2go_test) proof that
// GeneratedKeysProvider is reachable from outside the h2go package through
// sql.Conn.Raw + a direct driver-level ExecContext, and that a sql.Result
// returned by db.Exec intentionally does NOT expose it because database/sql
// wraps driver results in its own unexported type.
//
// MATURITY_ROUND_II_PLAN.md Task 3 (finding 4).

package h2go_test

import (
	"context"
	"database/sql/driver"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/rom35-cz/h2go"
)

// TestIntegration_GeneratedKeysProviderExternal verifies, from an external
// package's point of view:
//  1. the driver-level result implements h2go.GeneratedKeysProvider,
//  2. GetGeneratedKeys returns the full key result,
//  3. a sql.Result from db.Exec does NOT implement it (documented wrapping),
//  4. LastInsertId keeps working unchanged through database/sql.
func TestIntegration_GeneratedKeysProviderExternal(t *testing.T) {
	url := os.Getenv("JDBC_URL")
	user := os.Getenv("JDBC_USER")
	pw := os.Getenv("JDBC_PASSWORD")
	if url == "" || user == "" {
		t.Skip("integration test skipped: env not available")
	}

	cfg, err := h2go.ParseDSN(url)
	if err != nil {
		t.Fatalf("ParseDSN: %v", err)
	}
	h2go.MergeCredentials(cfg, user, pw)
	cfg.GeneratedKeysMode = h2go.GeneratedKeysAuto
	cfg.GeneratedKeysModeSet = true

	db, err := h2go.OpenDB(cfg)
	if err != nil {
		t.Fatalf("OpenDB: %v", err)
	}
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	table := fmt.Sprintf("gk_ext_%d", time.Now().UnixNano())
	_, err = db.ExecContext(ctx, "CREATE TABLE "+table+" ("+
		"id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "+
		"note VARCHAR(50))")
	if err != nil {
		t.Fatalf("CREATE TABLE: %v", err)
	}
	t.Cleanup(func() {
		_, _ = db.ExecContext(context.Background(), "DROP TABLE IF EXISTS "+table)
	})

	// (3) The documented negative case: database/sql wraps the driver result.
	wrappedRes, err := db.ExecContext(ctx, "INSERT INTO "+table+" (note) VALUES (?)", "wrapped")
	if err != nil {
		t.Fatalf("wrapped INSERT: %v", err)
	}
	if _, ok := wrappedRes.(h2go.GeneratedKeysProvider); ok {
		t.Error("sql.Result unexpectedly implements GeneratedKeysProvider; " +
			"database/sql result wrapping behaviour changed — update docs")
	}

	// (4) LastInsertId unchanged on the standard path.
	firstID, err := wrappedRes.LastInsertId()
	if err != nil {
		t.Fatalf("LastInsertId via sql.Result: %v", err)
	}
	if firstID <= 0 {
		t.Errorf("LastInsertId = %d, want > 0", firstID)
	}

	// (1)+(2) Driver-level access via Raw.
	sqlConn, err := db.Conn(ctx)
	if err != nil {
		t.Fatalf("db.Conn: %v", err)
	}
	defer sqlConn.Close()

	var gotColumn string
	var gotID int64
	err = sqlConn.Raw(func(raw any) error {
		c := raw.(driver.Conn) // *h2go.conn
		res, err := c.(driver.ExecerContext).ExecContext(ctx,
			"INSERT INTO "+table+" (note) VALUES ('direct')", nil)
		if err != nil {
			return err
		}
		gkp, ok := res.(h2go.GeneratedKeysProvider)
		if !ok {
			return fmt.Errorf("driver.Result (%T) does not implement h2go.GeneratedKeysProvider", res)
		}
		keys := gkp.GetGeneratedKeys()
		if keys == nil || len(keys.Rows) != 1 || len(keys.Columns) < 1 {
			return fmt.Errorf("unexpected generated keys shape: %+v", keys)
		}
		gotColumn = keys.Columns[0]
		id, ok := keys.Rows[0][0].(int64)
		if !ok {
			return fmt.Errorf("generated key type %T, want int64", keys.Rows[0][0])
		}
		gotID = id
		return nil
	})
	if err != nil {
		t.Fatalf("Raw driver-level access: %v", err)
	}

	if gotColumn != "ID" {
		t.Errorf("generated key column = %q, want ID", gotColumn)
	}
	if gotID <= 0 {
		t.Errorf("generated key value = %d, want > 0", gotID)
	}
	if gotID == firstID {
		t.Errorf("second insert reused first identity value %d", firstID)
	}
}
