#!/bin/sh
# Start a second local H2 TCP server with TLS enabled (-tcpSSL) on port 9093,
# using the keystore generated by gen-tls-certs.sh. DSN for clients:
#   jdbc:h2:ssl://localhost:9093/<database>
dir=$(dirname "$0")
if [ ! -f "$dir/tls/keystore.p12" ]; then
  sh "$dir/gen-tls-certs.sh"
fi
java \
  -Djavax.net.ssl.keyStore="$dir/tls/keystore.p12" \
  -Djavax.net.ssl.keyStorePassword=h2gotest \
  -cp "$dir/h2-2.4.240.jar:$H2DRIVERS:$CLASSPATH" \
  org.h2.tools.Server -tcp -tcpPort 9093 -tcpSSL -tcpAllowOthers -ifNotExists -baseDir $dir/data
